language: python
sudo: required
python:
    - 3.6.1
    - 3.6.2
    - 3.6.3
    - 3.6.4
    - 3.6.5
    - 3.6.6
    - 3.7.7
    - 3.8.3
services:
    - rabbitmq
install:
    - travis_retry pip install -e .
    - travis_retry pip install -Ur requirements.txt
    - pip freeze
script:
    - pycodestyle --ignore E203,W503,E501 --exclude proto_build,build,tmp .
    - travis_retry py.test --cov=./ tests/
    - tomodachi run tests/run_example_service.py
    - python tomodachi.py -v
    - python tomodachi.py --dependency-versions
    - mypy ./
    - python setup.py check -r -s
after_success:
    - codecov
