[tool.black]
line-length = 120
target_version = ["py37", "py38"]
include = '\.pyi?$'
exclude = '\.git/|\.mypy_cache/|\.venv/|\.pytest_cache/|\.vscode/|__pycache__/|build/|dist/|proto_build/|syntax_error_service\.py'

[tool.isort]
profile = "black"
line_length = 120
known_first_party = "tomodachi,run_test_service_helper,proto_build"
skip = ".mypy_cache,__pycache__"
